version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432"
    networks:
      - scrapy4paws-network

  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    environment:
      - POSTGRES_HOST=${DB_HOST}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_PORT=${DB_PORT}
      - API_URL=${API_URL}
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - scrapy4paws-network

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    environment:
      - API_URL=${API_URL}
      - STREAMLIT_SERVER_PORT=${STREAMLIT_SERVER_PORT:-8501}
      - STREAMLIT_SERVER_ADDRESS=${STREAMLIT_SERVER_ADDRESS:-0.0.0.0}
    ports:
      - "${STREAMLIT_SERVER_PORT:-8501}:${STREAMLIT_SERVER_PORT:-8501}"
    depends_on:
      - api
    networks:
      - scrapy4paws-network

volumes:
  postgres_data:

networks:
  scrapy4paws-network:
    driver: bridge 