version: '3.8'

services:
  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    volumes:
      - ..:/app
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=scrapy4paws
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    depends_on:
      postgres:
        condition: service_healthy
    command: >
      sh -c "alembic upgrade head &&
             python scripts/main.py"

  postgres:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=scrapy4paws
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: 